docker_hub:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - echo $DOCKER_HUB_PASSWORD | docker login --username $DOCKER_HUB_USER --password-stdin
  script:
    - cd .docker && docker build --no-cache -t hrnciarik/panther-php-symfony .
    - docker push hrnciarik/panther-php-symfony:latest
  only:
    - master

github:
  image: ruby:2.7
  stage: build
  script:
    - printenv
    - git push https://$GITHUB_TOKEN@github.com/hrnco/panther-php-symfony.git
  only:
    - master
